services:
  api:
    container_name: fastapp
    build: 
      context: ./
    command: bash -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    restart: always
    depends_on:
      - backend
    env_file: ./env_files/api.env
    ports:
      - "8000:8080"
    volumes:
      - ./:/usr/src/webapp

  db:
    container_name: pg_db
    image: postgres
    restart: always
    env_file: ./env_files/db.env
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - db-data:/var/lib/mysql

  backend:
    container_name: pgadmin
    image: dpage/pgadmin4
    env_file: ./env_files/db.env
    ports:
      - 5050:5050
    depends_on:
      - backend

volumes:
  db-data: