services:
  db:
    container_name: postgres_fastapp
    image: postgres
    restart: always
    expose:
      - "5432"
    env_file: ./env_files/db.env
    volumes:
      - db-data:/var/lib/postgresql/data

  backend:
    container_name: pgadmin_fastapp
    image: dpage/pgadmin4
    env_file: ./env_files/db.env
    depends_on: 
      - db
    ports:
      - "5050:80"
    expose:
      - "5050"
      
  api:
    container_name: fastapp
    build: 
      context: ./
    command: sh -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    restart: always
    env_file: ./env_files/api.env
    depends_on: 
      - db
    ports:
      - "8080:8000"
    volumes:
      - ./:/usr/src/webapp

  redis:
    container_name: redis_fastapp
    image: redis:7.0-alpine

  celery_worker:
    container_name: celery_worker_fastapp
    build: 
      context: ./worker
    command: celery -A celery_worker.celery worker --loglevel=info
    volumes:
      - .:/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - api
      - redis

  flower:
    container_name: flower_fastapp_fastapp
    build: 
      context: ./worker
    command: celery -A celery_worker.celery flower --port=5555
    ports:
      - 5555:5555
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - api
      - redis
      - celery_worker

volumes:
  db-data: