services:
  db:
    container_name: postgres_fastapp
    image: postgres
    restart: always
    expose:
      - "5432"
    env_file: ./env_files/db.env
    volumes:
      - db-data:/var/lib/postgresql/data

  backend:
    container_name: pgadmin_fastapp
    image: dpage/pgadmin4
    env_file: ./env_files/db.env
    depends_on: 
      - db
    ports:
      - "5050:80"
    expose:
      - "5050"
      
  api:
    container_name: fastapp
    build: 
      context: ./
    command: sh -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    restart: always
    env_file: ./env_files/api.env
    depends_on: 
      - db
    ports:
      - "8080:8000"
    volumes:
      - ./:/usr/src/webapp

volumes:
  db-data: