services:
  db:
    container_name: pg_db
    image: postgres
    restart: always
    expose:
      - 5432
    env_file: ./env_files/db.env
    volumes:
      - db-data:/var/lib/mysql

  backend:
    container_name: pgadmin
    image: dpage/pgadmin4
    env_file: ./env_files/db.env
    depends_on: 
      - db
    ports:
      - 5050:5050
    expose:
      - 5050
      
  api:
    container_name: fastapp
    build: 
      context: ./
    command: sh -c "alembic revision --autogenerate -m 'First migration' && alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    restart: always
    env_file: ./env_files/api.env
    depends_on: 
      - db
    ports:
      - "8080:8000"
    volumes:
      - ./:/usr/src/webapp

volumes:
  db-data: