"""First migration

Revision ID: 9b30e6a8f3e5
Revises: b082607b73de
Create Date: 2023-02-03 23:54:05.823322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b30e6a8f3e5'
down_revision = 'b082607b73de'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
